name: Dispatch workflows on PR changes

on:
  pull_request:
    types:
      - opened
      - ready_for_review
      - review_request_removed
      - synchronize
      - reopened

jobs:
  dispatch:
    name: Dispatch workflows on PR changes
    runs-on: ubuntu-latest
    steps:
      - name: Start the "Tests" workflow
        run: |
          curl -sSL \
            -X POST \
            -H "Accept: application/vnd.github.v3+json" \
            -d "branch=${{ env.GITHUB_REF }}" \
            -d "event=push" \
            https://api.github.com/repos/${{ github.repository }}/actions/workflows/tests.yml/dispatches \
            | jq -r '.'
