name: Dispatch workflows on `git push`

on: [push]

jobs:
  dispatch:
    name: Dispatch workflows on `git push`
    runs-on: ubuntu-latest
    steps:
      - name: Start the "Tests" workflow
        run: |
          # extract branch/tag name from ref
          ref="${{ github.ref }}"
          case "$ref" in
            refs/heads/*) ref=$(echo "$ref" | cut -c12-) ;;
            refs/tags/*) ref=$(echo "$ref" | cut -c11-) ;;
            *)
              echo "Could not parse ref '$ref'" 1>&2
              exit 1
              ;;
          esac
          # trigger
          curl -v -S -L \
            -X POST \
            -H 'Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' \
            -H "Accept: application/vnd.github.v3+json" \
            -d '{ "ref":"'"$ref"'" }' \
            https://api.github.com/repos/${{ github.repository }}/actions/workflows/tests.yml/dispatches \
            | jq -r '.'
